FROM --platform=linux/amd64 alpine:latest 

ARG OCTOPUS_CLI_VERSION=2.4.0

RUN apk update && apk upgrade && apk add --no-cache bash curl

RUN curl -L https://github.com/OctopusDeploy/cli/raw/main/scripts/install.sh | VERSION=v$OCTOPUS_CLI_VERSION bash

ENTRYPOINT [""]