name: Build octopus-cli-ci Docker image
on:
  push:
    branches: 
    - main
    paths:
    - ci-image/** 
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

env:
   REGISTRY_IMAGE: octopuslabs/octopus-cli-ci

jobs:
  
  get-octopus-cli-version:
    runs-on: windows-latest
    outputs: 
      VERSION: ${{ steps.choco.outputs.VERSION }}
      CONTINUE: ${{ steps.choco.outputs.CONTINUE }}
    steps:
      - uses: actions/checkout@v3
      - id: choco
        name: Compare latest version with container
        run: |
          $chocoInformationRaw = choco info octopus-cli --limitoutput
          $versionOutput = ($chocoInformationRaw.Split("|"))[1]

          [System.Version]$version = $null
          $versionParsed = [System.Version]::TryParse($versionOutput, [ref]$version)
          if(-not $versionParsed) {
              Write-Host "Unable to parse '$versionOutput' as a valid version. Won't continue"
              echo "CONTINUE=No" >> $env:GITHUB_OUTPUT
          }
          else {
              $versionToCompare = "$($version.Major).$($version.Minor).$($version.Build)"
              Write-Host "Parsed version as $versionToCompare"
              
              echo "VERSION=$versionToCompare" >> $env:GITHUB_OUTPUT
          
              $response = try {
                $repositoryTags = Invoke-RestMethod "https://registry.hub.docker.com/v2/repositories/${{ env.REGISTRY_IMAGE }}/tags"
                Write-Host "Retrieval successful!"
              } catch [System.Net.WebException] { 
                $_.Exception.Response 
                Write-Host "Retrieval failed!!"
              }
              
              if ($null -eq $response)
              {
                $matchingTag = $repositoryTags.results | Where-Object {$_.Name -eq $versionToCompare}
                
                if ($null -ne $matchingTag)
                {
                  Write-Host "Docker container already has latest version."
                  echo "CONTINUE=No" >> $env:GITHUB_OUTPUT
                }
                else
                {
                  Write-Host "vNext Octopus CLI has been updated, create new image."
                  echo "CONTINUE=Yes" >> $env:GITHUB_OUTPUT
                }
              }
              else
              {
                if ($response.StatusCode.value__ -eq 404)
                {
                  Write-Host "No tags exist for repo, assuming first build."
                  echo "CONTINUE=Yes" >> $env:GITHUB_OUTPUT
                }
              }
          }
          
        shell: powershell
          
  build-linux:
    needs: [get-octopus-cli-version]
    if: ${{ needs.get-octopus-cli-version.outputs.CONTINUE == 'Yes' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker Hub login
        env:
          USERNAME: ${{ secrets.DOCKER_HUB_USER }}
          PASSWORD: ${{ secrets.DOCKER_HUB_PAT }}
        run: docker login --username $USERNAME --password "$PASSWORD"

      - name: Build the alpine docker image
        env: 
          VERSION_NUMBER: ${{ needs.get-octopus-cli-version.outputs.VERSION }}
        run: docker build ./ci-image/alpine --build-arg OCTOPUS_CLI_VERSION=${{ needs.get-octopus-cli-version.outputs.VERSION }} --tag ${{ env.REGISTRY_IMAGE }}:${{ needs.get-octopus-cli-version.outputs.VERSION }}-alpine --tag ${{ env.REGISTRY_IMAGE }}:latest-alpine
        
      - name: Push the alpine image
        env:
          VERSION_NUMBER: ${{ needs.get-octopus-cli-version.outputs.VERSION }}
        run: |
          docker push ${{ env.REGISTRY_IMAGE }}:$VERSION_NUMBER-alpine
          docker push ${{ env.REGISTRY_IMAGE }}:latest-alpine

  build-docker-manifest:
    needs: [build-linux, get-octopus-cli-version]
    if: ${{ needs.get-octopus-cli-version.outputs.CONTINUE == 'Yes' }}
    runs-on: ubuntu-latest

    steps:
      - name: Docker hub login
        env:
          USERNAME: ${{ secrets.DOCKER_HUB_USER }}
          PASSWORD: ${{ secrets.DOCKER_HUB_PAT }}
        run: docker login --username $USERNAME --password "$PASSWORD"

      - name: Build manifests
        env:
          VERSION_NUMBER: ${{ needs.get-octopus-cli-version.outputs.VERSION }}
        run: |
          docker manifest create ${{ env.REGISTRY_IMAGE }}:latest ${{ env.REGISTRY_IMAGE }}:latest-alpine
          docker manifest create ${{ env.REGISTRY_IMAGE }}:$VERSION_NUMBER ${{ env.REGISTRY_IMAGE }}:$VERSION_NUMBER-alpine

      - name: Push manifests
        env:
          VERSION_NUMBER: ${{ needs.get-octopus-cli-version.outputs.VERSION }}
        run: |
          docker manifest push ${{ env.REGISTRY_IMAGE }}:latest
          docker manifest push ${{ env.REGISTRY_IMAGE }}:$VERSION_NUMBER
